name: guardspot
description: The GuardSpot frontend for Android, iOS and web.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  get_it: ^7.1.3
  injectable: ^1.4.0
  validators2: ^3.0.0
  cupertino_icons: ^0.1.3
  intl: ^0.17.0
  i18next: ^0.4.0-nullsafety
  fimber: ^0.6.0
  dio: ^4.0.0
  web_socket_channel: ^2.1.0
  json_annotation: ^4.0.0
  shared_preferences: ^2.0.5
  rxdart: ^0.26.0
  provider: ^5.0.0
  url_launcher: ^6.0.2
  os_detect: ^2.0.0
  auto_route: ^2.2.0
  camera_camera: ^2.0.1

  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0

  grouped_list: ^4.0.0
  file_picker: ^3.0.1

  # Android & iOS only
  geolocator: ^7.0.3
  google_maps_flutter: ^2.0.5
  flutter_local_notifications: ^5.0.0

  # Web only
  google_maps_flutter_web: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
  build_runner: ^2.0.3
  auto_route_generator: ^2.1.0
  json_serializable: ^4.0.2
  injectable_generator: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/map/
    - assets/localizations/de/
